import Script from "next/script";
import Footer from "./components/layout-components/Footer";
import NavBar from "./components/layout-components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
        <Script
          src="/assets/js/material-kit-customized.js"
          strategy="lazyOnload"
          type="module"
        ></Script>
      </body>
    </html>
  );
}
