import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}

        <Script
          src="/assets/js/core/popper.min.js"
          strategy="lazyOnload"
        ></Script>
        <Script
          src="/assets/js/core/bootstrap.min.js"
          strategy="lazyOnload"
        ></Script>
        <Script
          src="/assets/js/plugins/perfect-scrollbar.min.js"
          strategy="lazyOnload"
        ></Script>
      </body>
    </html>
  );
}
